Update safari-technology-preview from 118,001-92171-20210105-8d3c22a7-e518-4758-8df4-fe87c4fa078a to 122
Homebrew/homebrew-cask-versions pull request #10589
Opened 2021-03-26 13:43 UTC by VergeDX

Created with `brew bump-cask-pr`.

2021-03-27 22:16 UTC, stephenwade requested changes

2021-03-27 22:16 UTC, stephenwade commented on Casks/safari-technology-preview.rb
>      sha256 "8ffd7f83166106992cfc65a9760efe61578b55e1d8a1c960d56867f2048bd953"
```suggestion
    version "122,071-16079-20210311-bca5754c-86ef-489e-b268-3beb8d730736"
    sha256 "0c95147ab1f975114bd7da4b55f0f5d7d43042a1174ff89e218805dc50119903"
```

2021-03-27 22:16 UTC, stephenwade commented on Casks/safari-technology-preview.rb
> +    sha256 "b3762454597c1bd7ece748880d4247a73f3c3b879b9023d6c2e444c2889e28f4"
```suggestion
    version "122,071-16085-20210311-811b32d3-ef27-45c3-9ab9-1f70ac4c47e0"
    sha256 "0f8fcba70a17459322f923f196f56e8e222da960c4260de18ea38adbae0d5980"
```

2021-03-30 03:37 UTC, miccal commented
Closing in favour of https://github.com/Homebrew/homebrew-cask-versions/pull/10608.

2021-03-30 03:37 UTC, closed without merging