Update vmware-fusion-tech-preview
Homebrew/homebrew-cask-versions pull request #11010
Opened 2021-05-20 17:47 UTC by yurikoles

* port changes from stable
* add livechek
* sort binaries
* old homepage is dead

Signed-off-by: Yurii Kolesnykov <root@yurikoles.com>

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

2021-05-20 20:06 UTC, yurikoles commented
Stable cask update is here: https://github.com/Homebrew/homebrew-cask/pull/106067

2021-05-20 20:36 UTC, vitorgalvao requested changes

2021-05-20 20:36 UTC, vitorgalvao commented on Casks/vmware-fusion-tech-preview.rb
> +    url "https://bit.ly/get-fusion-tp"
We need a proper official URL, not a redirect minification which can lead anywhere.

2021-05-20 20:36 UTC, vitorgalvao commented on Casks/vmware-fusion-tech-preview.rb
> +  desc "App to run other operating systems without rebooting"
```suggestion
  desc "Create, manage, and run virtual machinces"
```

2021-05-20 20:39 UTC, cho-m commented on Casks/vmware-fusion-tech-preview.rb
> +  desc "App to run other operating systems without rebooting"
I think you have a typo
`machinces` -> `machines`

2021-05-20 20:39 UTC, vitorgalvao commented on Casks/vmware-fusion-tech-preview.rb
> +  desc "App to run other operating systems without rebooting"
Indeed. Nice catch.

2021-05-20 20:42 UTC, yurikoles commented on Casks/vmware-fusion-tech-preview.rb
> +    url "https://bit.ly/get-fusion-tp"
This URL works since last summer, I don't know a better way to livecheck this app.
Anyway, we don't download an artifact from it and similar approach is used in [deezer cask]( https://github.com/cho-m/homebrew-cask/blob/ccd2c281a5236c16124a19535b8ec309afb88638/Casks/deezer.rb#L11).

2021-05-20 20:44 UTC, yurikoles commented on Casks/vmware-fusion-tech-preview.rb
> +    url "https://bit.ly/get-fusion-tp"
Old one gives 404.

2021-05-20 20:47 UTC, vitorgalvao commented on Casks/vmware-fusion-tech-preview.rb
> +    url "https://bit.ly/get-fusion-tp"
> and similar approach is used in [deezer cask](https://github.com/cho-m/homebrew-cask/blob/ccd2c281a5236c16124a19535b8ec309afb88638/Casks/deezer.rb#L11).

`deezer` has a proper URL. You’re using a `bit.ly` URL here.

2021-05-20 20:48 UTC, yurikoles commented on Casks/vmware-fusion-tech-preview.rb
> +    url "https://bit.ly/get-fusion-tp"
It's not me, it's they use it across all pages on their blog.

2021-05-20 20:49 UTC, vitorgalvao commented on Casks/vmware-fusion-tech-preview.rb
> +    url "https://bit.ly/get-fusion-tp"
Either way. Just use the URL that expands to.

2021-05-20 20:50 UTC, cho-m commented on Casks/vmware-fusion-tech-preview.rb
> +    url "https://bit.ly/get-fusion-tp"
Was about to comment that:
```
❯ curl -sI "https://bit.ly/get-fusion-tp" | grep location
location: http://www.vmware.com/go/get-fusion-tp
```

2021-05-20 20:51 UTC, yurikoles commented on Casks/vmware-fusion-tech-preview.rb
> +    url "https://bit.ly/get-fusion-tp"
Yes, you are right, there is actually a proper one behind it: http://www.vmware.com/go/get-fusion-tp

2021-05-20 21:00 UTC, yurikoles commented on Casks/vmware-fusion-tech-preview.rb
> +    url "https://bit.ly/get-fusion-tp"
Thanks for one-liner, @cho-m, it's much better than my stone man approach to run `curl -v <url>` and try to filter it with eyes, which I failed.

2021-05-21 00:38 UTC, miccal approved these changes

2021-05-21 00:38 UTC, merged