feat: modify `visual-studio-code-insiders` to use `:latest` version
Homebrew/homebrew-cask-versions pull request #13411
Opened 2022-02-28 15:44 UTC by thecesrom

Similar to #13398

>Discussed in https://github.com/Homebrew/discussions/discussions/3020
>
>The intention is to decrease burden on maintainers, infrastructure,
>and contributors, as this Cask updates daily.

CC'ing the most recent contributors: @hannesbraun, @owine

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-versions/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

2022-02-28 23:08 UTC, bevanjkay requested changes

2022-02-28 23:08 UTC, bevanjkay commented on Casks/visual-studio-code-insiders.rb
> +  url "https://update.code.visualstudio.com/api/update/#{arch}/insider/VERSION" do |version_page|
@thecesrom 
Can we use a static link here instead of the `do` block?

https://code.visualstudio.com/sha/download?build=insider&os=darwin

2022-02-28 23:15 UTC, thecesrom commented on Casks/visual-studio-code-insiders.rb
> +  url "https://update.code.visualstudio.com/api/update/#{arch}/insider/VERSION" do |version_page|
If it automatically detects the CPU architecture, I do think we can.

I do not own an M1 machine, but in my case it attempts to download `VSCode-darwin.zip`.

2022-02-28 23:46 UTC, bevanjkay commented on Casks/visual-studio-code-insiders.rb
> +  url "https://update.code.visualstudio.com/api/update/#{arch}/insider/VERSION" do |version_page|
@thecesrom It just needs to be
```ruby
  url "https://code.visualstudio.com/sha/download?build=insider&os=#{arch}"
```

2022-03-01 00:23 UTC, thecesrom commented on Casks/visual-studio-code-insiders.rb
> +  url "https://update.code.visualstudio.com/api/update/#{arch}/insider/VERSION" do |version_page|
`url` stanza has been modified as requested and all CI checks passed.

2022-03-01 00:34 UTC, bevanjkay approved these changes

2022-03-01 01:28 UTC, merged

2022-03-01 01:49 UTC, thecesrom commented
Thanks, @bevanjkay and @miccal