various: add zaps
Homebrew/homebrew-cask-versions pull request #16523
Opened 2023-04-26 13:50 UTC by razvanazamfirei

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-versions/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

2023-04-26 17:24 UTC, bevanjkay requested changes

2023-04-26 17:24 UTC, bevanjkay commented on Casks/google-japanese-ime-dev.rb
> +              "com.google.pkg.Keystone",
The keystone packages are common to all Google apps aren't can't be removed on uninstall. Have a look at a couple of other Google casks for reference.

2023-04-26 17:35 UTC, razvanazamfirei commented on Casks/google-japanese-ime-dev.rb
> +              "com.google.pkg.Keystone",
Changes made and moved to separate PR since it will likely require ci-skip-install.

2023-04-27 01:10 UTC, bevanjkay approved these changes

2023-04-27 01:10 UTC, merged