1password nightly
Homebrew/homebrew-cask-versions pull request #16645
Opened 2023-05-10 13:06 UTC by duffpop

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-versions/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

2023-05-10 13:41 UTC, bevanjkay commented
@duffpop We do not currently accept casks that contain `url do` blocks in this repo. 

Is there a link to download the `latest` version that we could use instead?

2023-05-10 13:53 UTC, duffpop commented
> @duffpop We do not currently accept casks that contain `url do` blocks in this repo.
> 
> Is there a link to download the `latest` version that we could use instead?

Oh... then I'm confused @bevanjkay; the [CONTRIBUTING.md](https://github.com/Homebrew/homebrew-cask-versions/blob/master/CONTRIBUTING.md) explicitly states:

> the use of a [url do block](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/url.md#using-a-block-to-defer-code-execution) in conjunction with version :latest and sha256 :no_check is encouraged, to ensure the latest version is always fetched

Has the suggested procedure for nightly builds changed? I assume the Contributing doc is outdated as the [url do block](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/url.md#using-a-block-to-defer-code-execution) links to a 404.

Annoyingly, there isn't a static resource one can download `latest` from; 1Password maintains a changelog that the aforementioned Casks utilise. I'm happy to host my own tap if there isn't a graceful way to tackle this Cask, though I'd welcome any feedback you have.

2023-05-11 07:02 UTC, miccal commented on Casks/1password-beta.rb
> +  conflicts_with cask: %w[1password homebrew/cask-versions/1password-nightly]
```suggestion
  conflicts_with cask: [
    "1password",
    "1password-nightly",
  ]
```

2023-05-11 07:02 UTC, miccal commented on Casks/1password-nightly.rb
> +  conflicts_with cask: %w[1password homebrew/cask-versions/1password-beta]
```suggestion
  conflicts_with cask: [
    "1password",
    "1password-beta",
  ]
```

2023-05-11 07:14 UTC, bevanjkay requested changes
Can you please re-add `auto_updates true`?

2023-05-11 07:14 UTC, bevanjkay commented on Casks/1password-nightly.rb
> +  end
```suggestion
  url "https://c.1password.com/dist/1P/mac8/1Password-latest.NIGHTLY-#{arch}.zip"
```

2023-05-20 17:21 UTC, reitermarkus commented on Casks/1password-beta.rb
> +    )
Leave this as a single line.

2023-05-28 15:14 UTC, closed without merging