Add Threema Multi Device Beta
Homebrew/homebrew-cask-versions pull request #17271
Opened 2023-07-28 19:53 UTC by joelfischerr

Threema is a paid cross-platform encrypted instant messaging app developed by Threema GmbH in Switzerland. The multi device beta introduces a new multi device functionality to the existing desktop app. I have included multi device in the cask name to clearly distinguish it from the previous desktop application which would also be available as a beta version.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-versions/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

2023-07-31 03:25 UTC, bevanjkay commented on Casks/threema-multi-device-beta.rb
> +cask "threema-multi-device-beta" do
@joelfischerr The token should be `threema-beta` according to the [token reference guidelines.](https://docs.brew.sh/Cask-Cookbook#token-reference)

2023-07-31 03:25 UTC, bevanjkay commented on Casks/threema-multi-device-beta.rb
> +  sha256 :no_check
@joelfischerr Because the url is versioned, we should have a shasum here instead of `:no_check`

2023-07-31 03:26 UTC, bevanjkay commented on Casks/threema-multi-device-beta.rb
> +  name "Threema Desktop 2.0 Beta"
```suggestion
  name "Threema"
```

2023-07-31 03:33 UTC, bevanjkay commented on Casks/threema-multi-device-beta.rb
> +  end
```suggestion
  livecheck do
    url "https://threema.ch/en/download-md"
    regex(/href=.*?threema[._-]desktop[._-]v?(\d+(?:(?:[.-]|(beta))+\d+)+)[._-]macos[._-]arm64\.dmg/i)
  end
```

2023-07-31 03:33 UTC, bevanjkay requested changes
@joelfischerr Please see requested changes

2023-07-31 04:31 UTC, joelfischerr commented
Thank you for the review!

I've made the requested changes. Your suggestions were not applied because I already pushed the first fixup commit and then Github wouldn't let me apply the now "outdated" suggestions.

2023-07-31 06:28 UTC, bevanjkay commented
@joelfischerr Thanks for the changes. Before I merge can you please confirm that this can be used alongside the stable version? If not we should add a `conflicts_with` stanza.

2023-08-01 14:41 UTC, joelfischerr commented
There is not stable version at the moment. Should we add the `conflicts_with` anyways to be sure nobody forgets to update it once the stable version is released?

2023-08-01 21:53 UTC, bevanjkay commented
@joelfischerr is this not the stable version?

https://github.com/Homebrew/homebrew-cask/blob/fa103d2c4550e4e3b2b7a4854681fc601a2cf393/Casks/threema.rb

2023-08-01 21:55 UTC, joelfischerr commented
I believe it is a different product using different identifiers. It doesn't
conflict with that one for sure.

On Tue, 1 Aug 2023 at 23:53, Bevan Kay ***@***.***> wrote:

> @joelfischerr <https://github.com/joelfischerr> is this not the stable
> version?
>
>
> https://github.com/Homebrew/homebrew-cask/blob/fa103d2c4550e4e3b2b7a4854681fc601a2cf393/Casks/threema.rb
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Homebrew/homebrew-cask-versions/pull/17271#issuecomment-1661150030>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAR6M7QVSWDAXA6MBQTXC2LXTF3GDANCNFSM6AAAAAA235LPFI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-08-01 23:04 UTC, bevanjkay commented
@joelfischerr I would say that it is the beta for the second version of the same cask, but it looks like it doesn't share an preferences, so both can be installed concurrently.

2023-08-01 23:04 UTC, bevanjkay approved these changes

2023-08-01 23:04 UTC, merged