temurin17 17.0.9
Homebrew/homebrew-cask-versions pull request #18129
Opened 2023-10-20 13:19 UTC by chenrui333

Created by `brew bump`

---

Created with `brew bump-cask-pr`.

2023-10-20 22:43 UTC, razvanazamfirei submitted a review, later dismissed

2023-10-23 09:22 UTC, gdams requested changes
We can't merge this until Temurin 17.0.9 has been shipped for x64 too

2023-10-23 22:26 UTC, bevanjkay commented
@gdams We can split the version based on architecture? Unless the release it not far away?

2023-10-24 11:59 UTC, gdams approved these changes

2023-10-24 12:02 UTC, merged