Add zed-preview cask
Homebrew/homebrew-cask-versions pull request #19124
Opened 2024-01-29 11:52 UTC by timfjord

A preview version of the Zed editor - https://zed.dev/releases/preview

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-versions/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --cask --new <cask>` worked successfully.
- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

2024-01-29 11:56 UTC, timfjord commented on Casks/zed-preview.rb
> +  conflicts_with cask: [
Regarding this one.
It doesn't really conflict with the stable release version, because the name of app is `Zed Preview.app`.
So we could change the `binary` to be something like
```ruby
binary "#{appdir}/Zed Preview.app/Contents/MacOS/cli", target: "zed-preview"
```
and remove the `conflicts_with`.

But the problem here is the app doesn't use `zed-preview` for the binary, so if someone tries to link from the app they will have two binaries for the same installation.
So I would probably keep the `conflicts_with` to avoid confusion and to follow the app defaults.

2024-01-29 11:57 UTC, timfjord commented on Casks/zed-preview.rb
> +  conflicts_with cask: [
And yes, if we agree on that I will go ahead and add the `conflicts_with` to the stable cask too.

2024-01-31 19:10 UTC, bevanjkay requested changes
Just one small formatting nitpick that unfortunately does not get picked up by `brew style` at the moment.

Otherwise looks great, and I agree with your assessment of the conflict.

2024-01-31 19:10 UTC, bevanjkay commented on Casks/zed-preview.rb
> +  ]
```suggestion
  conflicts_with cask: "zed"
```

Just a small formatting nitpick here, that doesn't currently get picked up by

2024-02-01 18:47 UTC, bevanjkay approved these changes

2024-02-02 14:31 UTC, krehel approved these changes

2024-02-02 14:31 UTC, merged