Add Paragon extFS for Mac 11
Homebrew/homebrew-cask-versions pull request #19848
Opened 2024-04-01 10:39 UTC by MTCoster

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-versions/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --cask --new <cask>` worked successfully.
- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

---

The only difference between versions 11 and 12 is the migration to the new licensing system. If you have a license in the old system, you must use version 11.

Per Paragon support:

> Using new Licensing Center is currently the only difference between these versions. [...] Download the compatible installer for this license using "Download" button, and remove current version.

2024-04-01 23:33 UTC, bevanjkay commented on Casks/paragon-extfs11.rb
> +  url "https://dl.paragon-software.com/demo/trial_extfs.dmg"
```suggestion
  url "https://dl.paragon-software.com/demo/trial_extfs#{version.major}.dmg"
```

2024-04-01 23:34 UTC, bevanjkay requested changes
Just one minor change and we should be good. Then add the reverse conflict on the `paragon-extfs` once this is merged.

2024-04-02 11:23 UTC, MTCoster commented
Very weird! Reverted

2024-04-02 11:31 UTC, bevanjkay approved these changes

2024-04-02 11:32 UTC, merged