add the development snapshot of FreeCAD
Homebrew/homebrew-cask-versions pull request #9863
Opened 2020-11-03 22:12 UTC by ipatch

the cask contains the conda build of FreeCAD 0.19_pre release

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.

	- updated formula with required URL stanza for separate URLs contained within the cask

- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask-versions/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-versions/search?q=is%3Aclosed&type=Issues).

- a previous cask was submitted over a year ago, but the 0.18 release of freecad has become quite dated and the 0.19 pre releases are recommended version to use as of November 2020

- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

2020-11-03 23:22 UTC, vitorgalvao requested changes

2020-11-03 23:22 UTC, vitorgalvao commented on Casks/freecad-pre.rb
> +  # Renamed to avoid conflict with other FreeCAD.app
Not a valid reason to rename. Please remove it.

2020-11-03 23:22 UTC, vitorgalvao commented on Casks/freecad-pre.rb
> +  name "FreeCAD 0.19_pre"
Versions are not part of the name.

2020-11-03 23:22 UTC, vitorgalvao commented on Casks/freecad-pre.rb
> +  # github.com/FreeCAD/FreeCAD/releases/download was verified as official when first introduced to the cask
Too much. `github.com/FreeCAD/FreeCAD` is enough.

2020-11-03 23:23 UTC, vitorgalvao approved these changes

2020-11-03 23:31 UTC, merged

2020-11-03 23:38 UTC, ipatch commented on Casks/freecad-pre.rb
> +  # Renamed to avoid conflict with other FreeCAD.app
i think you may miss highlighted certain lines. i appended `_pre` to the end of the app bundle name so this particular install would not conflict with prior `FreeCAD.app` install as

```shell
brew search freecad
```

shows,

```shell
==> Casks
freecad
```

```shell
brew cask info freecad
```

shows,

```shell
freecad: 0.18.4,16146
https://www.freecadweb.org/
Not installed
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/freecad.rb
==> Name
FreeCAD
==> Description
3D parametric modeler
==> Artifacts
FreeCAD.app (App)
==> Analytics
install: 331 (30 days), 1,133 (90 days), 3,784 (365 days)
```

it'd be wise / best practice to separate the pre release ie. 0.19 from the 0.18.4,16146 as the.0.18.4.xxxx is no longer actively taking any new features but is considered the stable release.

2020-11-03 23:38 UTC, ipatch commented on Casks/freecad-pre.rb
> +  name "FreeCAD 0.19_pre"
will submit update here in a sec

2020-11-03 23:39 UTC, ipatch commented on Casks/freecad-pre.rb
> +  # github.com/FreeCAD/FreeCAD/releases/download was verified as official when first introduced to the cask
will submit update in a sec

2020-11-05 03:40 UTC, vitorgalvao commented on Casks/freecad-pre.rb
> +  # Renamed to avoid conflict with other FreeCAD.app
> i appended `_pre` to the end of the app bundle name so this particular install would not conflict with prior `FreeCAD.app` install

Yes, I understood that. Still not a valid reason for renaming. See other casks for tons of precedent. If upstream doesn’t name their betas and the like any different, neither do we.

> it'd be wise / best practice to separate the pre release ie. 0.19 from the 0.18.4,16146 as the.0.18.4.xxxx is no longer actively taking any new features but is considered the stable release.

All the more reason to *not* separate them, because users should only be using one of them.